---
- name: Gather the installed version
  command: /opt/install4j9/bin/install4jc --version
  changed_when: false
  failed_when: false
  register: installed_install4j_version

- name: Install install4j (RedHat)
  package:
    name: "https://download-gcdn.ej-technologies.com/install4j/install4j_linux-x64_{{ install4j_version | replace('.', '_') }}.rpm"
    state: present
    disable_gpg_check: true
  when:
    - ansible_os_family == 'RedHat'
    - not (installed_install4j_version.stdout | default('') is search(install4j_version))
  become: true

- name: Install install4j (Debian)
  apt:
    deb: "https://download-gcdn.ej-technologies.com/install4j/install4j_linux-x64_{{ install4j_version | replace('.', '_') }}.deb"
    state: present
  when:
    - ansible_os_family == 'Debian'
    - not (installed_install4j_version.stdout | default('') is search(install4j_version))
  become: true

- name: Configure install4j vm options
  template:
    src: "install4j.vmoptions.j2"
    dest: /opt/install4j9/bin/install4j.vmoptions
    backup: false
    owner: root
    group: root
    mode: 0644
  become: true
